variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

image: maven:3-openjdk-11

include:
  - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository
    - telegram-bot/target
    - aws-lambda/target

stages:
  - build
  - test
  - verify

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

sast:
  stage: test

spotbugs-sast:
  variables:
    SAST_JAVA_VERSION: 11

coverage:
  stage: verify
  script:
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' count-the-days-bot/target/site/jacoco/jacoco.csv
  coverage: '/(\d+\.?\d*) \% covered/'
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

codacy:
  stage: verify
  script:
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r telegram-bot/target/site/jacoco/jacoco.xml -r aws-lambda/target/site/jacoco/jacoco.xml
  rules:
    - if: $CODACY_PROJECT_TOKEN
